config/routes.rb
Rails.application.routes.draw do
  resources :habitat_descriptions
  resources :habitats
  resources :animals
  resources :articles
  resources :quizzes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/habitat.rb
class Habitat < ApplicationRecord
    has_many :habitats
end

app/models/habitat_description.rb
class HabitatDescription < ApplicationRecord
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @start = params[:q] || ''
    @start = @start.downcase
    @animals = Animal.all
    @animals = @animals.sort{|a,b| a.search_name <=> b.search_name}
    matcher = @start.gsub('?','')
    if matcher.size > 0
      @animals=@animals.select{|a| a.search_name.downcase.match matcher}
    end
    render 'index'
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:search_name, :image_name, :habitat)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.fetch(:article, {})
    end
end

app/controllers/habitat_descriptions_controller.rb
class HabitatDescriptionsController < ApplicationController
  before_action :set_habitat_description, only: %i[ show edit update destroy ]

  # GET /habitat_descriptions or /habitat_descriptions.json
  def index
    @habitat_descriptions = HabitatDescription.all
  end

  # GET /habitat_descriptions/1 or /habitat_descriptions/1.json
  def show
  end

  # GET /habitat_descriptions/new
  def new
    @habitat_description = HabitatDescription.new
  end

  # GET /habitat_descriptions/1/edit
  def edit
  end

  # POST /habitat_descriptions or /habitat_descriptions.json
  def create
    @habitat_description = HabitatDescription.new(habitat_description_params)

    respond_to do |format|
      if @habitat_description.save
        format.html { redirect_to habitat_description_url(@habitat_description), notice: "Habitat description was successfully created." }
        format.json { render :show, status: :created, location: @habitat_description }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @habitat_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habitat_descriptions/1 or /habitat_descriptions/1.json
  def update
    respond_to do |format|
      if @habitat_description.update(habitat_description_params)
        format.html { redirect_to habitat_description_url(@habitat_description), notice: "Habitat description was successfully updated." }
        format.json { render :show, status: :ok, location: @habitat_description }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @habitat_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habitat_descriptions/1 or /habitat_descriptions/1.json
  def destroy
    @habitat_description.destroy

    respond_to do |format|
      format.html { redirect_to habitat_descriptions_url, notice: "Habitat description was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habitat_description
      @habitat_description = HabitatDescription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def habitat_description_params
      params.require(:habitat_description).permit(:habitat_type, :habitat_description)
    end
end

app/controllers/habitats_controller.rb
class HabitatsController < ApplicationController
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def index
    render 'index'

  end 

end	

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/habitat_descriptions_helper.rb
module HabitatDescriptionsHelper
end

app/helpers/habitats_helper.rb
module HabitatsHelper
end

app/views/animals/_animal.html.erb
<div id="<%= dom_id animal %>">
    <%= link_to "#{animal.search_name}", animal %>
</div>

app/views/animals/_animal_show.html.erb
<div id="<%= dom_id @animal %>">
  <h3>
    <%= @animal.search_name %>
  </h3> 
  <p>
    <strong>Is this animal Real:</strong>
    <%= @animal.real %> <br><br>
    <strong>Habitat:</strong>
    <%= @animal.habitat || "The real world" %>
  </p>
  <p>
    <% asset = "app/assets/images/real/#{@animal.image_name}.png" %>
    <% potter_asset = "app/assets/images#{@animal.image_name}.png" %>

    <% if File.exist?(Rails.root + asset) && @animal.habitat !='Harry Potter'%>
      <%= image_tag("/assets/real/#{@animal.image_name}.png", size: "500x500") %>
    <% elsif File.exist?(Rails.root + potter_asset)%>
      <%= image_tag ("#{@animal.image_name[1..-1]}.png") %>
    <% else %>
      <h2> So sorry, I couldn't find a Picture </h2>
        <img width=500px, height=500px src=
            <%= "https://7esl.com/wp-content/uploads/2020/12/#{@animal.image_name}-300x300.png"%>
        >
    <% end %>
  </p>

  <p>
    <strong>Habitat Type:</strong>
    <%= @animal.habitat_type %>
  </p>

</div>

app/views/animals/_autocomplete.html.erb
<div class='search'>
  <%= form_tag("/index", method: "get", id: 'search') do %>
  <input type="text" name="q" id="q" value="start" class='textbox', size="10">
  <% end %>
</div>

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
  <% if animal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :search_name, style: "display: block" %>
    <%= form.text_area :search_name %>
  </div>

  <div>
    <%= form.label :image_name, style: "display: block" %>
    <%= form.text_area :image_name %>
  </div>

  <div>
    <%= form.label :habitat, style: "display: block" %>
    <%= form.text_field :habitat %>
  </div>
  
  <div>
    <%= form.label :habitat_type, style: "display: block" %>
    <%= form.text_field :habitat_type %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Show this animal", @animal %> |
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/index.html.erb
<div class='body'>
 <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script> 

<%= javascript_include_tag 'packs/my_js' %>

<div id="animals" class="scroll">
  <% start = @start || 'bbb' %>
  <div class='search'>
    <%= form_tag("/animals", method: "get", id: 'search') do %>
      <input type="text" name="q" id="q" value="<%=start%>" class='textbox', size="10">
    <% end %>
  </div>

  <% @animals.each do |animal| %>
    <div id="<%= dom_id animal %>">
      <%= link_to "#{animal.search_name}", animal %>
    </div>
  <% end %>
</div>

</div>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/show.html.erb
<h3><%= link_to "Back to animals", animals_path %></h3>

<%= render 'animals/animal_show', locals: {animal: @animal} %>

<div>

  <%= link_to "Back to animals", animals_path %>

 
</div>

<br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br>
<%= link_to "Edit this animal", edit_animal_path(@animal) %> |
<br><br><br><br><br><br><br><br>
 <%= button_to "Destroy this animal", @animal, method: :delete %>

app/views/habitat_descriptions/_form.html.erb
<%= form_with(model: habitat_description) do |form| %>
  <% if habitat_description.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(habitat_description.errors.count, "error") %> prohibited this habitat_description from being saved:</h2>

      <ul>
        <% habitat_description.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :habitat_type, style: "display: block" %>
    <%= form.text_field :habitat_type %>
  </div>

  <div>
    <%= form.label :habitat_description, style: "display: block" %>
    <%= form.text_area :habitat_description, cols:100, rows:10 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<p>From _form </p>  
<% end %>

app/views/habitat_descriptions/_habitat_description.html.erb
<div id="<%= dom_id habitat_description %>">
  <p>
    <strong>Habitat type:</strong>
    <%= habitat_description.habitat_type %>
  </p>

  <p>
    <strong>Habitat description:</strong>
    <%= habitat_description.habitat_description %>
  </p>

</div>

app/views/habitat_descriptions/edit.html.erb
<h1>Editing habitat description</h1>

<%= render "form", habitat_description: @habitat_description %>

<br>

<div>
  <%= link_to "Show this habitat description", @habitat_description %> |
  <%= link_to "Back to habitat descriptions", habitat_descriptions_path %>
</div>

app/views/habitat_descriptions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Habitat descriptions</h1>

<div id="habitat_descriptions">
  <% @habitat_descriptions.each do |habitat_description| %>
    <%= render habitat_description %>
    <p>
      <%= link_to "Show this habitat description", habitat_description %>
    </p>
  <% end %>
</div>

<%= link_to "New habitat description", new_habitat_description_path %>

app/views/habitat_descriptions/new.html.erb
<h1>New habitat description</h1>

<%= render "form", habitat_description: @habitat_description %>

<br>

<div>
  <%= link_to "Back to habitat descriptions", habitat_descriptions_path %>
</div>

app/views/habitat_descriptions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @habitat_description %>

<div>
  <%= link_to "Edit this habitat description", edit_habitat_description_path(@habitat_description) %> |
  <%= link_to "Back to habitat descriptions", habitat_descriptions_path %>

<br><br><br><br><br><br><br><br>
  <%= button_to "Destroy this habitat description", @habitat_description, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

<%= javascript_include_tag "application" "data-turbolinks-track" => true %>
<html>
  <head>
    <title>Animals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>